<a href="https://colab.research.google.com/github/jinojustin30/ML-PROJECT-RED-WINE/blob/main/IS_Wine_Good.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt #importing libraries


Import Data and pre process it


In [ ]:
dataset = pd.read_csv('/content/winequality-red.csv')

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [ ]:
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [ ]:
x

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [ ]:
y

array([5, 5, 5, ..., 6, 5, 6])

Model building


In [ ]:
from sklearn.model_selection import train_test_split #training and testing data split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
plt.plot = (x_train,y_train,'b.')

In [ ]:
plt.plot=(x_test,y_test,'b.')

In [ ]:
len(x_train)

1279

Data is Standardised

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()

In [ ]:
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
x_test

array([[-0.29035759,  0.11489575, -1.39800201, ..., -0.33327714,
        -0.094006  , -0.93571984],
       [ 2.58935206, -1.27801096,  2.44893209, ..., -0.71741183,
         0.67786452,  0.37101854],
       [-0.69351694, -1.72374111,  1.14929219, ...,  0.49901469,
        -0.56900325,  1.86443382],
       ...,
       [-0.9814879 ,  1.81424193, -1.29403082, ...,  1.45935142,
        -0.33150463,  0.55769545],
       [ 0.6311495 , -1.05514589,  0.52546504, ..., -0.58936694,
        -0.21275531, -1.12239675],
       [ 0.11280176, -0.3308344 ,  0.00560908, ..., -0.97350163,
         1.15286177,  0.6510339 ]])

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
dcla = DecisionTreeClassifier()

In [ ]:
dcla.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
pred = dcla.predict(x_test)

In [ ]:
for i in range(len(x_test)):
    print(pred[i],y_test[i],pred[i]-y_test[i])

6 6 0
7 7 0
5 6 -1
5 5 0
6 6 0
7 7 0
5 6 -1
5 5 0
7 7 0
6 6 0
6 5 1
6 6 0
6 3 3
5 5 0
6 7 -1
6 6 0
5 5 0
5 5 0
6 5 1
5 6 -1
6 5 1
6 6 0
5 7 -2
6 6 0
5 5 0
5 5 0
6 5 1
5 5 0
5 4 1
6 6 0
5 5 0
6 5 1
6 5 1
4 5 -1
6 7 -1
6 6 0
6 6 0
6 6 0
5 5 0
6 6 0
6 6 0
6 6 0
7 7 0
5 6 -1
5 5 0
6 6 0
6 6 0
5 5 0
5 6 -1
6 5 1
5 5 0
6 5 1
5 6 -1
5 7 -2
5 8 -3
5 6 -1
6 6 0
6 6 0
6 6 0
7 6 1
6 5 1
5 5 0
7 6 1
5 5 0
5 5 0
4 5 -1
5 5 0
6 6 0
5 5 0
5 6 -1
7 6 1
5 5 0
5 6 -1
6 7 -1
6 5 1
6 6 0
6 6 0
6 6 0
7 6 1
6 6 0
6 6 0
6 5 1
6 6 0
4 5 -1
6 6 0
5 7 -2
4 5 -1
8 7 1
5 5 0
5 5 0
5 5 0
6 6 0
5 4 1
5 5 0
7 6 1
5 6 -1
6 6 0
5 5 0
6 5 1
6 6 0
6 6 0
6 6 0
6 5 1
6 6 0
7 6 1
5 5 0
5 5 0
6 5 1
6 6 0
6 5 1
6 6 0
7 6 1
6 4 2
7 6 1
5 6 -1
6 5 1
5 6 -1
6 6 0
6 6 0
5 5 0
5 5 0
6 4 2
6 5 1
6 6 0
6 6 0
5 5 0
5 6 -1
5 5 0
6 6 0
5 4 1
6 6 0
7 4 3
8 7 1
5 5 0
6 6 0
6 6 0
4 5 -1
5 6 -1
6 6 0
6 6 0
5 5 0
7 7 0
5 5 0
5 4 1
6 5 1
6 6 0
5 6 -1
5 6 -1
6 6 0
5 5 0
6 6 0
6 6 0
5 5 0
6 6 0
5 5 0
5 5 0
7 7 0
6 6 0
6 6 0
7 7 0
6 5 1
5 5 0


In [ ]:
from sklearn.preprocessing import StandardScaler 

In [ ]:
a_train = y_train.reshape(len(y_train),1)
a_test = y_test.reshape(len(y_test),1)

In [ ]:
x_sc = StandardScaler()
y_sc = StandardScaler()

In [ ]:
x_std_train = x_sc.fit_transform(x_train)
y_std_train = y_sc.fit_transform(a_train)

In [ ]:
x_std_test = x_sc.transform(x_test)
y_std_test = y_sc.transform(a_test)

In [ ]:
from sklearn.metrics import accuracy_score #accuracy measure

In [ ]:
accuracy_score(pred, y_test)
                              

0.60625

train on different algorithms 


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR #support vector machine

In [ ]:
from sklearn.preprocessing import PolynomialFeatures

In [ ]:
temp = PolynomialFeatures(degree=5)
temp = temp.fit_transform(x_train)

In [ ]:
temp

array([[ 1.        , -0.57832855, -1.25015283, ...,  0.69920392,
        -0.88810198,  1.12803305],
       [ 1.        , -0.29035759,  0.64420029, ..., -0.16594415,
        -0.19780977, -0.23579443],
       [ 1.        , -0.40554597,  0.11489575, ..., -0.11131822,
        -0.11615917, -0.12121064],
       ...,
       [ 1.        ,  1.20709143, -1.11086216, ...,  0.10300538,
         0.15342832,  0.22853419],
       [ 1.        , -0.34795178, -0.21940187, ..., -0.00371391,
        -0.02959255, -0.23579443],
       [ 1.        , -0.69351694,  0.17061201, ..., -0.04932655,
        -0.23858346, -1.15398426]])

In [ ]:
poly = PolynomialFeatures(degree=5)
poly = poly.fit_transform(x_test)

In [ ]:
poly

array([[ 1.00000000e+00, -2.90357588e-01,  1.14895745e-01, ...,
        -7.24016875e-03, -7.20674139e-02, -7.17346835e-01],
       [ 1.00000000e+00,  2.58935206e+00, -1.27801096e+00, ...,
         2.34678136e-02,  1.28447404e-02,  7.03036759e-03],
       [ 1.00000000e+00, -6.93516939e-01, -1.72374111e+00, ...,
         2.09831367e+00, -6.87547387e+00,  2.25286341e+01],
       ...,
       [ 1.00000000e+00, -9.81487903e-01,  1.81424193e+00, ...,
         1.90620885e-02, -3.20684513e-02,  5.39492598e-02],
       [ 1.00000000e+00,  6.31149497e-01, -1.05514589e+00, ...,
        -6.40029566e-02, -3.37649429e-01, -1.78127922e+00],
       [ 1.00000000e+00,  1.12801762e-01, -3.30834402e-01, ...,
         3.66745917e-01,  2.07105510e-01,  1.16954792e-01]])

In [ ]:
rfcla = RandomForestClassifier(n_estimators = 100)
rfreg = RandomForestRegressor(n_estimators=100)
dreg = DecisionTreeRegressor()
dcla = DecisionTreeClassifier()
lreg = LinearRegression()
kncla = KNeighborsClassifier()
sreg = SVR()

fit function

In [ ]:
rfcla.fit(x_train, y_train)
rfreg.fit(x_train, y_train)
dreg.fit(x_train, y_train)
dcla.fit(x_train, y_train)
lreg.fit(x_train, y_train)
kncla.fit(x_train, y_train)
sreg.fit(x_std_train, y_std_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [ ]:
rc_pred = rfcla.predict(x_test)
rr_pred = rfreg.predict(x_test)
dr_pred = dcla.predict(x_test)
dc_pred = dreg.predict(x_test)
kc_pred = kncla.predict(x_test)
lr_pred = lreg.predict(x_test)
sr_pred = sreg.predict(x_std_test)


In [ ]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score

In [ ]:
z = r2_score(y_test,dr_pred)
q = r2_score(y_test,rr_pred)
t = r2_score(y_test,lr_pred)
u = r2_score(y_std_test,sr_pred)

In [ ]:
print('decision tree regression')
z

decision tree regression


0.0624098616993819

In [ ]:
print('random forrest regression')
q

random forrest regression


0.5122316041960799

In [ ]:
print('linear regression')
t

linear regression


0.3583938237187567

In [ ]:
print('support vector regression')
u

support vector regression


0.4097273390718731

In [ ]:

q = np.sqrt(mean_squared_error(y_test,rr_pred))
t = np.sqrt(mean_squared_error(y_test,lr_pred))
u = np.sqrt(mean_squared_error(y_std_test,sr_pred))
z = np.sqrt(mean_squared_error(y_test,dr_pred))

In [ ]:
print('decision tree regression(error)')
z

decision tree regression(error)


0.7766112283504534

In [ ]:
print('random forrest regression(error)')
q

random forrest regression(error)


0.5601495336068755

In [ ]:
print('linear regression(error)')
t

linear regression(error)


0.6424382907335172

In [ ]:
print('support vector regression(error)')
u

support vector regression(error)


0.76235487904998

In [ ]:
print('random forrest classifier')
accuracy_score(rc_pred,y_test)

random forrest classifier


0.6875

In [ ]:
print('decision tree classifier')
accuracy_score(dc_pred,y_test)

decision tree classifier


0.66875

In [ ]:
print('k neighbors')
accuracy_score(kc_pred,y_test)

k neighbors


0.5375

wine quality is good
